# Generated by Django 4.1.4 on 2023-01-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(upload_to='')),
                ('product_id', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=20)),
                ('product_desc', models.CharField(max_length=150)),
            ],
        ),
    ]
